"""Mapping artiste → genre, maintenu manuellement.

Pourquoi ce fichier : l'API Spotify ne renvoie plus les genres sur l'objet
artiste (le champ existe mais arrive vide). Plutôt que d'ajouter une
dépendance à un troisième service, on résout le genre par cascade :

    1. ce mapping local (fiable sur le catalogue de démonstration)
    2. le genre proposé par le premier utilisateur qui dig le morceau
    3. aucun genre — DigsCover s'appuie alors sur ses autres signaux

Évolution prévue : import d'un dump MusicBrainz pour couvrir automatiquement
l'ensemble du catalogue.
"""
from difflib import get_close_matches


ARTIST_GENRES = {
    # ---- Boom Bap ----
    'nas': 'Boom Bap',
    '2pac': 'Boom Bap',
    'the notorious b.i.g.': 'Boom Bap',
    'a tribe called quest': 'Boom Bap',
    'wu-tang clan': 'Boom Bap',
    'de la soul': 'Boom Bap',
    'gang starr': 'Boom Bap',
    'the roots': 'Boom Bap',
    'j dilla': 'Boom Bap',
    'mobb deep': 'Boom Bap',
    'krs-one': 'Boom Bap',
    'rakim': 'Boom Bap',
    'black thought': 'Boom Bap',
    'big daddy kane': 'Boom Bap',
    'common': 'Boom Bap',
    'pharoahe monch': 'Boom Bap',
    'benny the butcher': 'Boom Bap',
    'conway the machine': 'Boom Bap',
    'roc marciano': 'Boom Bap',
    'boldy james': 'Boom Bap',
    'apollo brown': 'Boom Bap',
    'evidence': 'Boom Bap',
    'ka': 'Boom Bap',
    'guilty simpson': 'Boom Bap',
    'lord finesse': 'Boom Bap',
    'diamond d': 'Boom Bap',
    'dj premier': 'Boom Bap',
    'iam': 'Boom Bap',
    'ntm': 'Boom Bap',
    'mc solaar': 'Boom Bap',
    'oxmo puccino': 'Boom Bap',
    'lunatic': 'Boom Bap',
    'ali': 'Boom Bap',
    'fonky family': 'Boom Bap',
    "mafia k'1 fry": 'Boom Bap',
    'ministère a.m.e.r.': 'Boom Bap',
    'assassin': 'Boom Bap',
    'le rat luciano': 'Boom Bap',
    'casey': 'Boom Bap',
    'hugo tsr': 'Boom Bap',
    'furax barbarossa': 'Boom Bap',
    'deen burbigo': 'Boom Bap',
    'ateyaba': 'Boom Bap',
    'youssoupha': 'Boom Bap',
    'kery james': 'Boom Bap',
    'disiz': 'Boom Bap',
    'shurik’n': 'Boom Bap',
    'akhenaton': 'Boom Bap',
    'lino': 'Boom Bap',
    'médine': 'Boom Bap',
    'l’hexaler': 'Boom Bap',

    # ---- Drill ----
    'chief keef': 'Drill',
    'lil durk': 'Drill',
    'king von': 'Drill',
    'fbg duck': 'Drill',
    'fivio foreign': 'Drill',
    'sheff g': 'Drill',
    'sleepy hallow': 'Drill',
    'pop smoke': 'Drill',
    'central cee': 'Drill',
    'headie one': 'Drill',
    'unknown t': 'Drill',
    'digga d': 'Drill',
    'horrid1': 'Drill',
    'loski': 'Drill',
    'abra cadabra': 'Drill',
    'skengdo': 'Drill',
    'cb': 'Drill',
    'gazo': 'Drill',
    'nemzzz': 'Drill',
    'dutchavelli': 'Drill',
    'nito nb': 'Drill',
    'zola': 'Drill',
    'kalash criminel': 'Drill',
    'freeze corleone': 'Drill',
    'ashe 22': 'Drill',
    'guy2bezbar': 'Drill',
    'leto': 'Drill',
    'so la lune': 'Drill',
    'khali': 'Drill',
    'baby gang': 'Drill',
    'l2b': 'Drill',
    'sdm': 'Drill',
    'ronisia': 'Drill',

    # ---- Phonk ----
    'kordhell': 'Phonk',
    'mystic phonk': 'Phonk',
    'memphis cult': 'Phonk',
    'lxst cxntury': 'Phonk',
    'dvrst': 'Phonk',
    'ariis': 'Phonk',
    'interworld': 'Phonk',
    'moondeity': 'Phonk',
    'pharmacist': 'Phonk',
    'ghostface playa': 'Phonk',
    'youthx': 'Phonk',
    'zodiak': 'Phonk',
    'neffex': 'Phonk',
    'playa phonk': 'Phonk',
    'sxmpra': 'Phonk',
    'scarlxrd': 'Phonk',
    'dj smokey': 'Phonk',
    'raizhell': 'Phonk',
    'slowboy': 'Phonk',
    'mythic': 'Phonk',

    # ---- Cloud Rap ----
    'lil peep': 'Cloud Rap',
    'yung lean': 'Cloud Rap',
    'bladee': 'Cloud Rap',
    'lil tracy': 'Cloud Rap',
    'ghostemane': 'Cloud Rap',
    'pouya': 'Cloud Rap',
    'fat nick': 'Cloud Rap',
    'eric dingus': 'Cloud Rap',
    'wicca phase springs eternal': 'Cloud Rap',
    'smrtdeath': 'Cloud Rap',
    'lil b': 'Cloud Rap',
    'spaceghostpurrp': 'Cloud Rap',
    'audiobullys': 'Cloud Rap',
    'pnl': 'Cloud Rap',
    'lala &ce': 'Cloud Rap',
    'le diouck': 'Cloud Rap',

    # ---- Trap ----
    'future': 'Trap',
    'young thug': 'Trap',
    '21 savage': 'Trap',
    'migos': 'Trap',
    'gunna': 'Trap',
    'lil baby': 'Trap',
    'travis scott': 'Trap',
    'yo gotti': 'Trap',
    'jeezy': 'Trap',
    'gucci mane': 'Trap',
    'lil uzi vert': 'Trap',
    'kodak black': 'Trap',
    'moneybagg yo': 'Trap',
    'young dolph': 'Trap',
    'lil keed': 'Trap',
    'fredo santana': 'Trap',
    'offset': 'Trap',
    'quavo': 'Trap',
    'don toliver': 'Trap',
    'rich the kid': 'Trap',
    'a boogie wit da hoodie': 'Trap',
    'lil tjay': 'Trap',
    'yeat': 'Trap',
    'destroy lonely': 'Trap',
    'ken carson': 'Trap',
    'playboi carti': 'Trap',
    'ninho': 'Trap',
    'sch': 'Trap',
    'damso': 'Trap',
    'niska': 'Trap',
    'tiakola': 'Trap',
    'werenoi': 'Trap',
    'hamza': 'Trap',
    'jul': 'Trap',
    'naps': 'Trap',
    'lacrim': 'Trap',
    'da uzi': 'Trap',
    'koba lad': 'Trap',
    "heuss l'enfoiré": 'Trap',
    'plk': 'Trap',
    'sadek': 'Trap',
    'moha k': 'Trap',
    'gambi': 'Trap',
    'kidd keo': 'Trap',

    # ---- Grime ----
    'skepta': 'Grime',
    'stormzy': 'Grime',
    'wiley': 'Grime',
    'dizzee rascal': 'Grime',
    'aj tracey': 'Grime',
    'jme': 'Grime',
    'bugzy malone': 'Grime',
    'd double e': 'Grime',
    'p money': 'Grime',
    'lethal bizzle': 'Grime',
    'chip': 'Grime',
    'tinie tempah': 'Grime',
    'tinchy stryder': 'Grime',

    # ---- Hip-Hop ----
    'drake': 'Hip-Hop',
    'kendrick lamar': 'Hip-Hop',
    'j. cole': 'Hip-Hop',
    'kanye west': 'Hip-Hop',
    'eminem': 'Hip-Hop',
    'jay-z': 'Hip-Hop',
    '50 cent': 'Hip-Hop',
    '2 chainz': 'Hip-Hop',
    'rick ross': 'Hip-Hop',
    'lil wayne': 'Hip-Hop',
    'nicki minaj': 'Hip-Hop',
    'tyler, the creator': 'Hip-Hop',
    'schoolboy q': 'Hip-Hop',
    'asap rocky': 'Hip-Hop',
    'a$ap rocky': 'Hip-Hop',
    'meek mill': 'Hip-Hop',
    'freddie gibbs': 'Hip-Hop',
    'busta rhymes': 'Hip-Hop',
    'pusha t': 'Hip-Hop',
    'big sean': 'Hip-Hop',
    'jid': 'Hip-Hop',
    'logic': 'Hip-Hop',
    'chance the rapper': 'Hip-Hop',
    'mac miller': 'Hip-Hop',
    'ab-soul': 'Hip-Hop',
    'wale': 'Hip-Hop',
    'earl sweatshirt': 'Hip-Hop',
    'bas': 'Hip-Hop',
    'booba': 'Hip-Hop',
    'kaaris': 'Hip-Hop',
    'lomepal': 'Hip-Hop',
    'orelsan': 'Hip-Hop',
    'josman': 'Hip-Hop',
    'dinos': 'Hip-Hop',
    'alpha wann': 'Hip-Hop',
    'laylow': 'Hip-Hop',
    'vald': 'Hip-Hop',
    'bigflo & oli': 'Hip-Hop',
    'georgio': 'Hip-Hop',
    'sofiane': 'Hip-Hop',
    'rohff': 'Hip-Hop',
    'la fouine': 'Hip-Hop',
    "rim'k": 'Hip-Hop',
    'lefa': 'Hip-Hop',
    'sniper': 'Hip-Hop',
    "sexion d'assaut": 'Hip-Hop',
    'maître gims': 'Hip-Hop',
    'soprano': 'Hip-Hop',
    'black m': 'Hip-Hop',
    'dosseh': 'Hip-Hop',
    'alkpote': 'Hip-Hop',
    'prince waly': 'Hip-Hop',
    'isha': 'Hip-Hop',
    'caballero & jeanjass': 'Hip-Hop',
    'roméo elvis': 'Hip-Hop',
    'shay': 'Hip-Hop',
    'luv resval': 'Hip-Hop',
    'zed': 'Hip-Hop',
    'central': 'Hip-Hop',
    'la caution': 'Hip-Hop',
    'svp': 'Hip-Hop',
    'giggs': 'Hip-Hop',
    'nines': 'Hip-Hop',
    'dave': 'Hip-Hop',
    'fredo': 'Hip-Hop',
    'j hus': 'Hip-Hop',
    'mist': 'Hip-Hop',

    # ---- Amapiano ----
    'kabza de small': 'Amapiano',
    'dj maphorisa': 'Amapiano',
    'focalistic': 'Amapiano',
    'vigro deep': 'Amapiano',
    'mas musiq': 'Amapiano',
    'shakes & les': 'Amapiano',
    'sha sha': 'Amapiano',
    'tyler icu': 'Amapiano',
    'mkeyz': 'Amapiano',
    'young stunna': 'Amapiano',
    'major league djz': 'Amapiano',
    'mellow & sleazy': 'Amapiano',
    'busta 929': 'Amapiano',
    'dbn gogo': 'Amapiano',
    'leehleza': 'Amapiano',
    'mfr souls': 'Amapiano',
    'de mthuda': 'Amapiano',
    'sir trill': 'Amapiano',
    'toss': 'Amapiano',
    'kelly khumalo': 'Amapiano',

    # ---- Afrobeats ----
    'burna boy': 'Afrobeats',
    'wizkid': 'Afrobeats',
    'davido': 'Afrobeats',
    'rema': 'Afrobeats',
    'asake': 'Afrobeats',
    'tems': 'Afrobeats',
    'tiwa savage': 'Afrobeats',
    'ayra starr': 'Afrobeats',
    'fireboy dml': 'Afrobeats',
    'bnxn': 'Afrobeats',
    'ckay': 'Afrobeats',
    'omah lay': 'Afrobeats',
    'yemi alade': 'Afrobeats',
    'kizz daniel': 'Afrobeats',
    'tekno': 'Afrobeats',
    'ruger': 'Afrobeats',
    'seyi vibez': 'Afrobeats',
    'bella shmurda': 'Afrobeats',
    'adekunle gold': 'Afrobeats',
    'runtown': 'Afrobeats',
    'olamide': 'Afrobeats',
    'victony': 'Afrobeats',
    'libianca': 'Afrobeats',
    'darkoo': 'Afrobeats',
    'mohbad': 'Afrobeats',
    'shallipopi': 'Afrobeats',
    'young jonn': 'Afrobeats',
    'naira marley': 'Afrobeats',
    'fave': 'Afrobeats',
    'simi': 'Afrobeats',
    'chike': 'Afrobeats',
    'fally ipupa': 'Afrobeats',
    "innoss'b": 'Afrobeats',
    'franglish': 'Afrobeats',
    'singuila': 'Afrobeats',
    'dadju': 'Afrobeats',
    'french montana': 'Afrobeats',

    # ---- Reggaeton ----
    'bad bunny': 'Reggaeton',
    'j balvin': 'Reggaeton',
    'daddy yankee': 'Reggaeton',
    'ozuna': 'Reggaeton',
    'karol g': 'Reggaeton',
    'anuel aa': 'Reggaeton',
    'feid': 'Reggaeton',
    'rauw alejandro': 'Reggaeton',
    'myke towers': 'Reggaeton',
    'nicky jam': 'Reggaeton',
    'arcangel': 'Reggaeton',
    'de la ghetto': 'Reggaeton',
    'chencho corleone': 'Reggaeton',
    'drefquila': 'Reggaeton',
    'sech': 'Reggaeton',
    'quevedo': 'Reggaeton',
    'mora': 'Reggaeton',
    'eladio carrion': 'Reggaeton',
    'cazzu': 'Reggaeton',
    'natti natasha': 'Reggaeton',
    'kali uchis': 'Latin',

    # ---- Dancehall ----
    'vybz kartel': 'Dancehall',
    'shenseea': 'Dancehall',
    'popcaan': 'Dancehall',
    'masicka': 'Dancehall',
    'skillibeng': 'Dancehall',
    'koffee': 'Dancehall',
    'spice': 'Dancehall',
    'movado': 'Dancehall',
    'aidonia': 'Dancehall',
    'busy signal': 'Dancehall',
    'beenie man': 'Dancehall',
    'bounty killer': 'Dancehall',
    'chronic law': 'Dancehall',
    'jahmiel': 'Dancehall',
    'alkaline': 'Dancehall',
    'jahvillani': 'Dancehall',
    'rajahwild': 'Dancehall',
    'jahshii': 'Dancehall',
    'byron messia': 'Dancehall',
    'malie donn': 'Dancehall',
    'najeeriii': 'Dancehall',

    # ---- Reggae ----
    'bob marley': 'Reggae',
    'peter tosh': 'Reggae',
    'burning spear': 'Reggae',
    'dennis brown': 'Reggae',
    'gregory isaacs': 'Reggae',
    'yellowman': 'Reggae',
    'damian marley': 'Reggae',
    'ziggy marley': 'Reggae',
    'chronixx': 'Reggae',
    'protoje': 'Reggae',
    'luciano': 'Reggae',
    'steel pulse': 'Reggae',
    'beres hammond': 'Reggae',
    'tenor saw': 'Reggae',
    'half pint': 'Reggae',

    # ---- Zouk ----
    "kassav'": 'Zouk',
    'jocelyne béroard': 'Zouk',
    'francky vincent': 'Zouk',
    'slaï': 'Zouk',
    'warren': 'Zouk',
    'perle lama': 'Zouk',
    'fanny j': 'Zouk',
    'admiral t': 'Zouk',
    'kalash': 'Zouk',
    'jahyanaï': 'Zouk',
    'nu look': 'Zouk',
    'klass': 'Zouk',
    't-vice': 'Zouk',
    'carimi': 'Zouk',

    # ---- Latin ----
    'shakira': 'Latin',
    'enrique iglesias': 'Latin',
    'selena': 'Latin',
    'gloria estefan': 'Latin',
    'celia cruz': 'Latin',
    'vicente fernandez': 'Latin',
    'juan gabriel': 'Latin',
    'natanael cano': 'Latin',
    'peso pluma': 'Latin',
    'grupo firme': 'Latin',
    'mana': 'Latin',

    # ---- Gospel ----
    'kirk franklin': 'Gospel',
    'tasha cobbs leonard': 'Gospel',
    'maverick city music': 'Gospel',
    'marvin sapp': 'Gospel',
    'tamela mann': 'Gospel',
    'fred hammond': 'Gospel',
    'cece winans': 'Gospel',
    'donnie mcclurkin': 'Gospel',
    'jj hairston': 'Gospel',
    'jason nelson': 'Gospel',
    'yolanda adams': 'Gospel',
    'travis greene': 'Gospel',
    'isaac carree': 'Gospel',
    'dorinda clark-cole': 'Gospel',
    'kierra sheard': 'Gospel',
    'koryn hawthorne': 'Gospel',
    'tasha page-lockhart': 'Gospel',
    'smokie norful': 'Gospel',
    'maurette brown clark': 'Gospel',
    'lecrae': 'Gospel',
    'tobymac': 'Gospel',
    'for king & country': 'Gospel',
    'mali music': 'Gospel',
    'kiki sheard': 'Gospel',
    'donald lawrence': 'Gospel',

    # ---- Soul ----
    'marvin gaye': 'Soul',
    'stevie wonder': 'Soul',
    'aretha franklin': 'Soul',
    'al green': 'Soul',
    'otis redding': 'Soul',
    'sam cooke': 'Soul',
    'donny hathaway': 'Soul',
    'luther vandross': 'Soul',
    'alicia keys': 'Soul',
    'mary j. blige': 'Soul',
    'joss stone': 'Soul',
    'amy winehouse': 'Soul',
    'anderson .paak': 'Soul',
    'leon bridges': 'Soul',
    'lee fields': 'Soul',
    'durand jones & the indications': 'Soul',
    'charles bradley': 'Soul',
    'sharon jones & the dap-kings': 'Soul',
    'ett james': 'Soul',
    'osebi benson': 'Soul',

    # ---- Funk ----
    'james brown': 'Funk',
    'parliament': 'Funk',
    'funkadelic': 'Funk',
    'george clinton': 'Funk',
    'bootsy collins': 'Funk',
    'earth, wind & fire': 'Funk',
    'chic': 'Funk',
    'rick james': 'Funk',
    'kool & the gang': 'Funk',
    'the commodores': 'Funk',
    'the meters': 'Funk',
    'tower of power': 'Funk',
    'sly & the family stone': 'Funk',
    'kool keith': 'Funk',
    'bruno mars': 'Funk',
    'mark ronson': 'Funk',
    'vulfpeck': 'Funk',
    'ghost-note': 'Funk',
    'lettuce': 'Funk',
    'the brand new heavies': 'Funk',

    # ---- Jazz ----
    'miles davis': 'Jazz',
    'john coltrane': 'Jazz',
    'charlie parker': 'Jazz',
    'thelonious monk': 'Jazz',
    'duke ellington': 'Jazz',
    'ella fitzgerald': 'Jazz',
    'billie holiday': 'Jazz',
    'herbie hancock': 'Jazz',
    'wynton marsalis': 'Jazz',
    'kamasi washington': 'Jazz',
    'esperanza spalding': 'Jazz',
    'ramsey lewis': 'Jazz',
    'bill evans': 'Jazz',
    'stan getz': 'Jazz',
    'lee morgan': 'Jazz',
    'jaco pastorius': 'Jazz',
    'cannonball adderley': 'Jazz',
    'art blakey': 'Jazz',
    'dave brubeck': 'Jazz',
    'chick corea': 'Jazz',

    # ---- Blues ----
    'b.b. king': 'Blues',
    'muddy waters': 'Blues',
    'howlin wolf': 'Blues',
    'john lee hooker': 'Blues',
    'robert johnson': 'Blues',
    'buddy guy': 'Blues',
    'stevie ray vaughan': 'Blues',
    't-bone walker': 'Blues',
    'freddie king': 'Blues',
    'elmore james': 'Blues',
    'bieber': 'Blues',
    'joan armatrading': 'Blues',
    'bonnie raitt': 'Blues',
    'gary clark jr.': 'Blues',
    'joe bonamassa': 'Blues',
    'shemekia copeland': 'Blues',
    'keb mo': 'Blues',
    'rory gallagher': 'Blues',
    'james cotton': 'Blues',
    'pinetop perkins': 'Blues',

    # ---- Jersey Club ----
    'dj smallz 732': 'Jersey Club',
    'ceejay the dj': 'Jersey Club',
    'tootone': 'Jersey Club',
    'killa kam': 'Jersey Club',
    'miia': 'Jersey Club',
    'shygirl': 'Jersey Club',
    'sliink': 'Jersey Club',
    'bandmanrill': 'Jersey Club',
    'jersey club hero': 'Jersey Club',
    'club angel': 'Jersey Club',
    'bobby shmurda': 'Jersey Club',
    'cash cobain': 'Jersey Club',
    'blaqbonez': 'Jersey Club',
    't pain': 'Jersey Club',
    'ice spice': 'Jersey Club',
    'lolawolf': 'Jersey Club',
    'nate dawg': 'Jersey Club',
    'yvngxchris': 'Jersey Club',
    'r3 da chilliman': 'Jersey Club',
    'luh tyler': 'Jersey Club',

    # ---- Drum & Bass ----
    'sub focus': 'Drum & Bass',
    'metrik': 'Drum & Bass',
    'pendulum': 'Drum & Bass',
    'chase & status': 'Drum & Bass',
    'netsky': 'Drum & Bass',
    'andy c': 'Drum & Bass',
    'bou': 'Drum & Bass',
    'dimension': 'Drum & Bass',
    'fred v': 'Drum & Bass',
    'delta heavy': 'Drum & Bass',
    'wilkinson': 'Drum & Bass',
    'high contrast': 'Drum & Bass',
    'nu:tone': 'Drum & Bass',
    'klute': 'Drum & Bass',
    'calyx & teebee': 'Drum & Bass',
    'kommando': 'Drum & Bass',
    'roni size': 'Drum & Bass',
    'seba': 'Drum & Bass',
    'technimatic': 'Drum & Bass',
    'tantrum desire': 'Drum & Bass',

    # ---- Garage ----
    'artful dodger': 'Garage',
    'craig david': 'Garage',
    'so solid crew': 'Garage',
    
    
    'george fitzgerald': 'Garage',
    'roy davis jr.': 'Garage',
    'santé': 'Garage',
    'joy orbison': 'Garage',
    'the streets': 'Garage',
    'shola ama': 'Garage',
    'kele le roc': 'Garage',
    'room 5': 'Garage',
    'ice cream': 'Garage',
    
    'm.i.a.': 'Garage',
    'mala': 'Garage',
    'bashy': 'Garage',
    'dem 2': 'Garage',
    'el-b': 'Garage',

    # ---- House ----
    
    'justice': 'House',
   
   
    
   
    
    'agoria': 'House',
    'petit biscuit': 'House',
    'bon entendeur': 'House',
    'röyksopp': 'House',
    'the chemical brothers': 'House',
    'calvin harris': 'House',
    'fred again..': 'House',
    'four tet': 'House',
    'silk city': 'House',
    'polo & pan': 'House',
    'mk': 'House',
    'gorgon city': 'House',
    'camelphat': 'House',



    # ---- Ambient ----
    'brian eno': 'Ambient',
    'aphex twin': 'Ambient',
    'harold budd': 'Ambient',
    'stars of the lid': 'Ambient',
    'biosphere': 'Ambient',
    'tim hecker': 'Ambient',
    'william basinski': 'Ambient',
    'oneohtrix point never': 'Ambient',
    'fennesz': 'Ambient',
    'rival consoles': 'Ambient',
    'max richter': 'Ambient',
    'heilung': 'Ambient',
    'tycho': 'Ambient',
    'loscil': 'Ambient',
    'geotic': 'Ambient',
    'gas': 'Ambient',
    'moby': 'Ambient',
    'helios': 'Ambient',
    'andrew chalk': 'Ambient',
    'hammock': 'Ambient',

    # ---- Electro ----
    'kraftwerk': 'Electro',
    'daft punk': 'Electro',
 
    'gesaffelstein': 'Electro',
    'dj snake': 'Electro',
    
    'kavinsky': 'Electro',
    
    
    
    'the prodigy': 'Electro',
    'deadmau5': 'Electro',
    'madeon': 'Electro',
    'zedd': 'Electro',
    'alan walker': 'Electro',
    'avicii': 'Electro',
    'armin van buuren': 'Electro',
    'skrillex': 'Electro',
    'flume': 'Electro',
    
}

def lookup_genre(artist_name, fuzzy=True):
    """Cherche le genre d'un artiste dans le mapping local.

    Deux passes :
        1. correspondance exacte (rapide, fiable)
        2. correspondance approximative (rattrape les variantes d'orthographe :
           "orel san" → "orelsan", "asap rocky" → "a$ap rocky")

    Le seuil de 0.85 est volontairement haut : mieux vaut ne rien trouver que
    classer un artiste dans le mauvais genre.
    """
    if not artist_name:
        return None

    key = artist_name.strip().lower()

    # 1. Exact
    exact = ARTIST_GENRES.get(key)
    if exact:
        return exact

    if not fuzzy:
        return None

    # 2. Approximatif
    matches = get_close_matches(key, ARTIST_GENRES.keys(), n=1, cutoff=0.85)
    return ARTIST_GENRES[matches[0]] if matches else None
